### ISSUE TITLE
unzip error for RESULTS.zip file in 'open_data/norne_simplified' folder

### ISSUE THREAD

**Issue by ajikmr** [Skoltech-CHR/DeepField#5]
Hello.
Please look at RESULTS.zip file. I am trying '06.Rates_calculation' tutorial file. 
zip file size is too small and is most probably empty.
Thanks.

**Comment by illarionovEA** [comment]
Hi! thank you for noting this issue. The reason is that we exceeded GitHub LHS limits. We provide a separate link to Dropbox where the file RESULTS.zip can be downloaded: https://www.dropbox.com/sh/09ebxa6u24gu2cn/AABVoOa3f3tDvWNTCPdnZGo4a?dl=0

**Comment by ajikmr** [comment]
Thank you very much.
