### ISSUE TITLE
dataset.calculate_statistics() error

### ISSUE THREAD

**Issue by UnconvRS** [Skoltech-CHR/DeepField#6]
Greetings,

Thanks for sharing this work! 

I went through the tutorials but got stuck in the calculation of the statistics for the FieldDataset in Tutorial #8 (Dataset and Sample). The cell, and error message obtained are pasted below. 

I should mention that the STATES shape from the previous cell yields a dimension of: [1, 248, 5, 46, 112, 22]. Is this what you expect?

Any comments on how to fix this will be much appreciated.  

Thanks,
Femi

***************************************************************************************
dataset = FieldDataset(src=field, sample_attrs=sample_attrs, allow_change_preloaded=True)
dataset.calculate_statistics()
sample = next(iter(dataset))
***************************************************************************************
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [15], in <cell line: 2>()
      1 dataset = FieldDataset(src=field, sample_attrs=sample_attrs, allow_change_preloaded=True)
----> 2 dataset.calculate_statistics()
      3 sample = next(iter(dataset))

File ~/anaconda3/envs/py3p8/lib/python3.8/site-packages/DeepField-0.1.0-py3.8.egg/deepfield/datasets/datasets.py:610, in FieldDataset.calculate_statistics(self)
    607         maxim[comp] = {attr: [] for attr in self.sample_attrs[comp]}
    609 for i in range(len(self)):
--> 610     m, m_sq, mn, mx = self._get_model_statistics(i)
    611     for comp in m:#pylint:disable=consider-using-dict-items
    612         for attr in m[comp]:

File ~/anaconda3/envs/py3p8/lib/python3.8/site-packages/DeepField-0.1.0-py3.8.egg/deepfield/datasets/datasets.py:635, in FieldDataset._get_model_statistics(self, idx)
    633 def _get_model_statistics(self, idx):
    634     """Get mean and mean of squares for the attributes of the model."""
--> 635     sample = self._get_sample(idx)
    636     mean, mean_of_squares, minim, maxim = {}, {}, {}, {}
    637     for comp in sample.keys():

File ~/anaconda3/envs/py3p8/lib/python3.8/site-packages/DeepField-0.1.0-py3.8.egg/deepfield/datasets/datasets.py:180, in FieldDataset._get_sample(self, idx)
    178     if isinstance(self.preloaded[idx], FieldSample):
    179         return self.preloaded[idx]
--> 180     model = self._get_preloaded(idx)
    182 sample = {}
    183 getter_kwargs = dict(
    184     sequence_subset=sequence_subset, fill_invalid_neighbours=INVALID_VALUE_FILLER, neighbouring_radius=1
    185 )

File ~/anaconda3/envs/py3p8/lib/python3.8/site-packages/DeepField-0.1.0-py3.8.egg/deepfield/datasets/datasets.py:236, in FieldDataset._get_preloaded(self, idx)
    234             model.wells.drop_outside()
    235         if model.meta['MODEL_TYPE'] == 'ECL':
--> 236             model.wells.compute_events(grid=model.grid)
    237 else:
    238     assert model.state.spatial == self.unravel_model

File ~/anaconda3/envs/py3p8/lib/python3.8/site-packages/DeepField-0.1.0-py3.8.egg/deepfield/field/decorators.py:225, in instance_check.<locals>.decorator.<locals>.wrapper(self, *args, **kwargs)
    222 if not valid(self):
    223     raise ValueError('State of {} is not valid for applying {}.'
    224                      .format(self.__class__.__name__, method.__name__))
--> 225 return method(self, *args, **kwargs)

File ~/anaconda3/envs/py3p8/lib/python3.8/site-packages/DeepField-0.1.0-py3.8.egg/deepfield/field/decorators.py:120, in apply_to_each_segment.<locals>.decorator(self, *args, **kwargs)
    118     if not include_groups and segment.is_group:
    119         continue
--> 120     res.append(method(self, segment, *args, **kwargs))
    121 if isinstance(res[0], self.__class__):
    122     return self

File ~/anaconda3/envs/py3p8/lib/python3.8/site-packages/DeepField-0.1.0-py3.8.egg/deepfield/field/wells.py:521, in Wells.compute_events(self, segment, grid, attr)
    519 wcon = wcon.sort_values('DATE').reset_index(drop=True)
    520 df['DATE'] = wcon['DATE']
--> 521 dref_index = np.argmin(segment.perforated_blocks()[:, 2])
    522 dref_index = segment.perforated_blocks()[:, :3][dref_index]
    523 df['DREF'] = grid.cell_centroids[dref_index[0], dref_index[1], dref_index[2]][2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by illarionovEA** [comment]
Hi! Thank you for exploring the DeepField framework!

yes, the state’s shape [1, 248, 5, 46, 112, 22] is correct. It corresponds to batch, time, channels, x, y, and z dimensions. However, we reproduced the issue you reported and fixed it the PR #7.
